### ISSUE TITLE
是否能够支持一下网易云课堂？

### ISSUE THREAD

**Issue by JamesHopbourn** [theFool32/163OpenCourse_playbackRate#3]
你好，请问能够支持一下网易云课堂吗？按道理来说这两个是通用的，但是实际测试没有效果，希望能够支持一下，谢谢。

**Comment by theFool32** [comment]
@JamesHopbourn 两个的方式似乎不一样。
替代方法可以考虑用HTML5播放器，然后用HTML5播放器的速度控制插件, 比如[Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?utm_source=chrome-app-launcher-info-dialog)

**Comment by JamesHopbourn** [comment]
谢谢
